# Figures for Lecture 5 (Exploratory analyses I)
###############################################
#
# Every figure on the Lecture 5 slides is generated by this script, so the
# slides can't drift away from the code students are shown. Run from the
# project root:
#
#   source("R_scripts/Lecture_05_figures.R")
#
# Output goes to lectures/figures/. All of it uses AVONET, which students
# already met in Lecture 4.

  avonet <- read.csv("data/Avonet/AVONET1_BirdLife.csv")

  fig_dir <- "lectures/figures"

  if (!dir.exists(fig_dir)) dir.create(fig_dir, recursive = TRUE)

  open_png <- function(name, width = 900, height = 650) {
    png(file.path(fig_dir, name), width = width, height = height, res = 110)
  }


# 1. The histogram that tells you nothing -----------------------------------

  # 99.9% of 11,009 species fall in the first bin, because the range runs from
  # a 1.9 g hummingbird to a 111 kg ostrich.

  open_png("05_01_hist_raw.png")

    hist(avonet$Mass,
         main = "hist(avonet$Mass)",
         xlab = "Body mass (g)",
         col  = "grey80")

  dev.off()


# 2. The same data on a log scale -------------------------------------------

  open_png("05_02_hist_log.png")

    hist(log10(avonet$Mass),
         main   = "hist(log10(avonet$Mass))",
         xlab   = "log10 body mass (g)",
         breaks = 40,
         col    = "grey80")

  dev.off()


# 3. Mass vs wing length, untransformed -------------------------------------

  # Everything is crushed against the y axis and the correlation looks weak.

  open_png("05_03_scatter_raw.png")

    plot(avonet$Mass, avonet$Wing.Length,
         xlab = "Mass (g)",
         ylab = "Wing length (mm)",
         main = "r = 0.35",
         pch  = 16,
         cex  = 0.4,
         col  = rgb(0, 0, 0, 0.3))

  dev.off()


# 4. The same plot on log-log axes ------------------------------------------

  # The relationship appears, and so do two very different kinds of odd point:
  # the five kiwi at 0.1 mm (a placeholder, not a measurement) and the ratites
  # at the top right (extreme, but real).

  open_png("05_04_scatter_log.png")

    plot(avonet$Mass, avonet$Wing.Length,
         log  = "xy",
         xlab = "Mass (g)",
         ylab = "Wing length (mm)",
         main = 'plot(..., log = "xy")   r = 0.89',
         pch  = 16,
         cex  = 0.4,
         col  = rgb(0, 0, 0, 0.3))

    kiwi <- avonet[avonet$Family1 == "Apterygidae", ]

    points(kiwi$Mass, kiwi$Wing.Length, pch = 1, cex = 2, col = "red", lwd = 2)

    text(x = 200, y = 0.1, labels = "5 kiwi, wing = 0.1 mm", col = "red", pos = 2)

    ostrich <- avonet[avonet$Mass > 100000, ]

    points(ostrich$Mass, ostrich$Wing.Length, pch = 1, cex = 2, col = "blue", lwd = 2)

    text(x = 90000, y = 220, labels = "ostrich", col = "blue", pos = 1)

  dev.off()


# 5. A continuous response split by a categorical predictor ------------------

  open_png("05_05_boxplot.png", width = 950)

    par(mar = c(5, 4, 3, 1))

    boxplot(log10(Mass) ~ Trophic.Level,
            data = avonet,
            main = "boxplot(log10(Mass) ~ Trophic.Level)",
            xlab = "",
            ylab = "log10 body mass (g)",
            col  = "grey85")

  dev.off()


# 6. A single categorical variable ------------------------------------------

  open_png("05_06_barplot.png", width = 950)

    par(mar = c(8, 4, 3, 1))

    barplot(sort(table(avonet$Habitat), decreasing = TRUE),
            main = "barplot(table(avonet$Habitat))",
            ylab = "Number of species",
            las  = 2,
            col  = "grey70")

  dev.off()


  message("Wrote 6 figures to ", fig_dir)
